[workspace]
authors = ["Bjarne Herben <bjarne@bepadata.nl>"]
channels = ["conda-forge"]
name = "heerbaart-service"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]
serve = "python -m api"
stage = "python pipeline.py"

[dependencies]
python = ">=3.12,<3.13"

[pypi-dependencies]
fastapi = ">=0.121.0, <0.122"
httpx = ">=0.28.1, <0.29"
python-dotenv = ">=1.2.1, <2"
uvicorn = ">=0.52.1, <0.53"
python-multipart = ">=0.0.20, <0.1"
pydantic = ">=2.11, <3"
openai = ">=2, <3"
pymupdf = ">=1.26, <2"

[feature.dev.pypi-dependencies]
ruff = ">=0.15.16, <0.16"

[environments]
prod = {features = []}
dev = {features = ["dev"]}
