"""Fixed Rev.D expression formulas from the saved STAP2-11 contracts.

The seven article-table values are deliberately not included.
"""


STEP2_EXPRESSIONS = (
    ('STEP2_EDGE_BREAK', '0.2', 'mm'),
    ('STEP2_EDGE_BREAK_ANGLE', '45', 'deg'),
    ('STEP2_HOLES_PER_FLANGE', '12', 'Integer'),
    ('STEP2_HOLE_PITCH', '360 / STEP2_HOLES_PER_FLANGE', 'deg'),
    ('STEP2_HOLE_PHASE', '15', 'deg'),
    ('STEP2_HOLE_DEPTH', 'FB', 'mm'),
    ('STEP2_LEFT_SEED_X', '-600 / 2 + FR', 'mm'),
    ('STEP2_RIGHT_SEED_X', '600 / 2 - FR', 'mm'),
    ('STEP2_SEED_Y', 'DL / 2 * cos(STEP2_HOLE_PHASE)', 'mm'),
    ('STEP2_SEED_Z', 'DL / 2 * sin(STEP2_HOLE_PHASE)', 'mm'),
)


STEP3_EXPRESSIONS = (
    ('STEP3_FLAT_OFFSET', '120', 'mm'),
    ('STEP3_SIDE_FLAT_OFFSET', '115', 'mm'),
    ('STEP3_CENTER_PAD_HALF_WIDTH', '81 / 2', 'mm'),
    ('STEP3_SIDE_PAD_Y_CENTER', '124.8', 'mm'),
    ('STEP3_SIDE_PAD_Y_WIDTH', '80', 'mm'),
    ('STEP3_DIAGONAL_PAD_Y_CENTER', '153.04', 'mm'),
    ('STEP3_DIAGONAL_PAD_Y_WIDTH', '40', 'mm'),
    ('STEP3_DIAGONAL_TANGENT_HALF', '48.99', 'mm'),
)


STEP4_EXPRESSIONS = (
    ('STEP4_THREAD_ANGLE_RIGHT', '0', 'deg'),
    ('STEP4_THREAD_ANGLE_UPPER_LEFT', '150', 'deg'),
    ('STEP4_THREAD_ANGLE_LOWER_LEFT', '210', 'deg'),
    ('STEP4_THREAD_ENTRY_RADIUS', 'FA / 2', 'mm'),
    ('STEP4_LEFT_FLANGE_CENTER_X', '-600 / 2 + FR + FB / 2', 'mm'),
    ('STEP4_RIGHT_FLANGE_CENTER_X', '600 / 2 - FR - FB / 2', 'mm'),
    ('STEP4_THREAD_RIGHT_Y', 'STEP4_THREAD_ENTRY_RADIUS * sin(STEP4_THREAD_ANGLE_RIGHT)', 'mm'),
    ('STEP4_THREAD_RIGHT_Z', 'STEP4_THREAD_ENTRY_RADIUS * cos(STEP4_THREAD_ANGLE_RIGHT)', 'mm'),
    ('STEP4_THREAD_UPPER_LEFT_Y', 'STEP4_THREAD_ENTRY_RADIUS * sin(STEP4_THREAD_ANGLE_UPPER_LEFT)', 'mm'),
    ('STEP4_THREAD_UPPER_LEFT_Z', 'STEP4_THREAD_ENTRY_RADIUS * cos(STEP4_THREAD_ANGLE_UPPER_LEFT)', 'mm'),
    ('STEP4_THREAD_LOWER_LEFT_Y', 'STEP4_THREAD_ENTRY_RADIUS * sin(STEP4_THREAD_ANGLE_LOWER_LEFT)', 'mm'),
    ('STEP4_THREAD_LOWER_LEFT_Z', 'STEP4_THREAD_ENTRY_RADIUS * cos(STEP4_THREAD_ANGLE_LOWER_LEFT)', 'mm'),
    ('STEP4_THREAD_DEPTH', '24', 'mm'),
    ('STEP4_DRILL_DEPTH', '30', 'mm'),
    ('STEP4_THREAD_TAP_DRILL_DIAMETER', '10.3', 'mm'),
    ('STEP4_THREAD_TIP_ANGLE', '140', 'deg'),
    ('STEP4_THREAD_CHAMFER_DIAMETER', '12.3', 'mm'),
    ('STEP4_THREAD_CHAMFER_ANGLE', '45', 'deg'),
)


STEP5_EXPRESSIONS = (
    ('STEP5_NPT_X_OFFSET', '150', 'mm'),
    ('STEP5_LEFT_NPT_X', '-STEP5_NPT_X_OFFSET', 'mm'),
    ('STEP5_RIGHT_NPT_X', 'STEP5_NPT_X_OFFSET', 'mm'),
    ('STEP5_NPT_Y', '0', 'mm'),
    ('STEP5_NPT_ENTRY_Z', 'STEP3_FLAT_OFFSET', 'mm'),
    ('STEP5_NPT_THREAD_DEPTH', '15', 'mm'),
    ('STEP5_NPT_TOTAL_DEPTH', '22', 'mm'),
    ('STEP5_NPT_START_CHAMFER_DIAMETER', '0.84 * 25.4', 'mm'),
    ('STEP5_NPT_START_CHAMFER_ANGLE', '45', 'deg'),
    ('STEP5_THROUGH_DIAMETER', '4', 'mm'),
    ('STEP5_THROUGH_DEPTH', 'STEP3_FLAT_OFFSET - 180 / 2', 'mm'),
)


STEP6_EXPRESSIONS = (
    ('STEP6_M8_PATTERN_PITCH_X', '60', 'mm'),
    ('STEP6_M8_PATTERN_PITCH_Y', '60', 'mm'),
    ('STEP6_M8_NEG_X', '-STEP6_M8_PATTERN_PITCH_X / 2', 'mm'),
    ('STEP6_M8_POS_X', 'STEP6_M8_PATTERN_PITCH_X / 2', 'mm'),
    ('STEP6_M8_NEG_Y', '-STEP6_M8_PATTERN_PITCH_Y / 2', 'mm'),
    ('STEP6_M8_POS_Y', 'STEP6_M8_PATTERN_PITCH_Y / 2', 'mm'),
    ('STEP6_M8_ENTRY_Z', 'STEP3_FLAT_OFFSET', 'mm'),
    ('STEP6_M8_THREAD_DEPTH', '13', 'mm'),
    ('STEP6_M8_TOTAL_DEPTH', '15', 'mm'),
    ('STEP6_M8_HOLE_TIP_ANGLE', '140.0', 'deg'),
    ('STEP6_M8_START_CHAMFER_DIAMETER', '8.3', 'mm'),
    ('STEP6_M8_START_CHAMFER_ANGLE', '45.0', 'deg'),
)


STEP7_EXPRESSIONS = (
    ('STEP7_M8_OUTER_SPAN_X', '360', 'mm'),
    ('STEP7_M8_INNER_SPAN_X', '140', 'mm'),
    ('STEP7_M8_ROW_PITCH', '40', 'mm'),
    ('STEP7_M8_ROW_OFFSET', 'STEP7_M8_ROW_PITCH / 2', 'mm'),
    ('STEP7_M8_NEG_Y', '-STEP7_M8_ROW_OFFSET', 'mm'),
    ('STEP7_M8_POS_Y', 'STEP7_M8_ROW_OFFSET', 'mm'),
    ('STEP7_M8_OUTER_NEG_X', '-STEP7_M8_OUTER_SPAN_X / 2', 'mm'),
    ('STEP7_M8_INNER_NEG_X', '-STEP7_M8_INNER_SPAN_X / 2', 'mm'),
    ('STEP7_M8_INNER_POS_X', 'STEP7_M8_INNER_SPAN_X / 2', 'mm'),
    ('STEP7_M8_OUTER_POS_X', 'STEP7_M8_OUTER_SPAN_X / 2', 'mm'),
    ('STEP7_M8_BODY_RADIUS', '250 / 2', 'mm'),
    ('STEP7_M8_ENTRY_OFFSET', 'STEP3_FLAT_OFFSET', 'mm'),
    ('STEP7_M8_ENTRY_Z_POS', 'STEP7_M8_ENTRY_OFFSET', 'mm'),
    ('STEP7_M8_ENTRY_Z_NEG', '-STEP7_M8_ENTRY_OFFSET', 'mm'),
    ('STEP7_M8_PROJECTION_MARGIN', '5', 'mm'),
    ('STEP7_M8_PROBE_Z_POS', 'STEP7_M8_BODY_RADIUS + STEP7_M8_PROJECTION_MARGIN', 'mm'),
    ('STEP7_M8_PROBE_Z_NEG', '-STEP7_M8_BODY_RADIUS - STEP7_M8_PROJECTION_MARGIN', 'mm'),
    ('STEP7_M8_SPOTFACE_DEPTH', 'sqrt(STEP7_M8_BODY_RADIUS * STEP7_M8_BODY_RADIUS - STEP7_M8_ROW_OFFSET * STEP7_M8_ROW_OFFSET) - STEP7_M8_ENTRY_OFFSET', 'mm'),
    ('STEP7_M8_SPOTFACE_DIAMETER', '15', 'mm'),
    ('STEP7_M8_SPOTFACE_BOTTOM_ANGLE', '0', 'deg'),
    ('STEP7_M8_THREAD_DEPTH', '13', 'mm'),
    ('STEP7_M8_TOTAL_DEPTH', '15', 'mm'),
    ('STEP7_M8_HOLE_TIP_ANGLE', '140.0', 'deg'),
    ('STEP7_M8_START_CHAMFER_DIAMETER', '8.3', 'mm'),
    ('STEP7_M8_START_CHAMFER_ANGLE', '45.0', 'deg'),
)


STEP8_EXPRESSIONS = (
    ('STEP8_DIAGONAL_FACE_START_X', '133', 'mm'),
    ('STEP8_DIAGONAL_FACE_WIDTH_X', '40', 'mm'),
    ('STEP8_DIAGONAL_FACE_CENTER_X', 'STEP8_DIAGONAL_FACE_START_X + STEP8_DIAGONAL_FACE_WIDTH_X / 2', 'mm'),
    ('STEP8_DIAGONAL_PATTERN_HALF_PITCH', '22.5', 'mm'),
    ('STEP8_DIAGONAL_H9_DIAMETER', '20', 'mm'),
    ('STEP8_DIAGONAL_H9_DEPTH', '25', 'mm'),
    ('STEP8_DIAGONAL_H9_CHAMFER_DIAMETER', '21.5', 'mm'),
    ('STEP8_DIAGONAL_H9_CHAMFER_ANGLE', '40', 'deg'),
    ('STEP8_DIAGONAL_PROJECTION_MARGIN', '5', 'mm'),
    ('STEP8_DIAGONAL_M8_THREAD_DEPTH', '13', 'mm'),
    ('STEP8_DIAGONAL_M8_TOTAL_DEPTH', '15', 'mm'),
    ('STEP8_DIAGONAL_M8_HOLE_TIP_ANGLE', '140.0', 'deg'),
    ('STEP8_DIAGONAL_M8_START_CHAMFER_DIAMETER', '8.3', 'mm'),
    ('STEP8_DIAGONAL_M8_START_CHAMFER_ANGLE', '45.0', 'deg'),
)


STEP9_EXPRESSIONS = (
    ('STEP9_SIDE_HOLE_INNER_X', '104.76', 'mm'),
    ('STEP9_SIDE_HOLE_OUTER_X', '144.76', 'mm'),
    ('STEP9_SIDE_HOLE_SPACING_X', 'STEP9_SIDE_HOLE_OUTER_X - STEP9_SIDE_HOLE_INNER_X', 'mm'),
    ('STEP9_SIDE_PATTERN_HALF_PITCH', '22.5', 'mm'),
    ('STEP9_SIDE_PATTERN_STAGGER', '1.38', 'mm'),
    ('STEP9_SIDE_H9_DIAMETER', '20', 'mm'),
    ('STEP9_SIDE_H9_CHAMFER_DIAMETER', '21.5', 'mm'),
    ('STEP9_SIDE_H9_CHAMFER_ANGLE', '40', 'deg'),
    ('STEP9_SIDE_PROJECTION_MARGIN', '5', 'mm'),
    ('STEP9_SIDE_M8_THREAD_DEPTH', '13', 'mm'),
    ('STEP9_SIDE_M8_TOTAL_DEPTH', '15', 'mm'),
    ('STEP9_SIDE_M8_HOLE_TIP_ANGLE', '140.0', 'deg'),
    ('STEP9_SIDE_M8_START_CHAMFER_DIAMETER', '8.3', 'mm'),
    ('STEP9_SIDE_M8_START_CHAMFER_ANGLE', '45.0', 'deg'),
)


STEP10_EXPRESSIONS = (
    ('STEP10_ROOT_RADIUS', '10', 'mm'),
    ('STEP10_OUTER_CHAMFER', '2', 'mm'),
    ('STEP10_OUTER_CHAMFER_ANGLE', '45', 'deg'),
)


STEP11_EXPRESSIONS = (
    ('STEP11_AXIAL_POSITION', '0', 'mm'),
    ('STEP11_ENTRY_RADIUS', '125', 'mm'),
    ('STEP11_M12_Y', 'STEP11_ENTRY_RADIUS * sqrt(3) / 2', 'mm'),
    ('STEP11_NPT_Y', '-STEP11_ENTRY_RADIUS * sqrt(3) / 2', 'mm'),
    ('STEP11_ENTRY_Z', 'STEP11_ENTRY_RADIUS / 2', 'mm'),
    ('STEP11_D4_DIAMETER', '4', 'mm'),
    ('STEP11_M12_THREAD_DEPTH', '9', 'mm'),
    ('STEP11_M12_DRILL_DEPTH', '14', 'mm'),
    ('STEP11_M12_TAP_DIAMETER', '10.3', 'mm'),
    ('STEP11_M12_TIP_ANGLE', '140.0', 'deg'),
    ('STEP11_M12_START_CHAMFER', '12.3', 'mm'),
    ('STEP11_M12_END_CHAMFER', '12.3', 'mm'),
    ('STEP11_M12_START_ANGLE', '45.0', 'deg'),
    ('STEP11_M12_END_ANGLE', '45.0', 'deg'),
    ('STEP11_NPT_THREAD_DEPTH', '10', 'mm'),
    ('STEP11_NPT_DRILL_DEPTH', '15', 'mm'),
    ('STEP11_NPT_TAP_DIAMETER', '11.115039999999999', 'mm'),
    ('STEP11_NPT_TIP_ANGLE', '118.0', 'deg'),
    ('STEP11_NPT_START_CHAMFER', '13.716', 'mm'),
    ('STEP11_NPT_END_CHAMFER', '13.716', 'mm'),
    ('STEP11_NPT_START_ANGLE', '45.0', 'deg'),
    ('STEP11_NPT_END_ANGLE', '45.0', 'deg'),
)
